// Code generated by "stringer -type=TokenType"; DO NOT EDIT.

package token

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Word-1]
	_ = x[String-2]
	_ = x[OpenBracket-3]
	_ = x[CloseBracket-4]
	_ = x[Comma-5]
}

const _TokenType_name = "WordStringOpenBracketCloseBracketComma"

var _TokenType_index = [...]uint8{0, 4, 10, 21, 33, 38}

func (i TokenType) String() string {
	i -= 1
	if i < 0 || i >= TokenType(len(_TokenType_index)-1) {
		return "TokenType(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _TokenType_name[_TokenType_index[i]:_TokenType_index[i+1]]
}
